### PR TITLE
Redefine and refactor aggregate

### LINKED ISSUE #28: Consistent timeline scope for TimeAggregates
In general, the scope of an aggregate starts with its associated time point `time` and has an interval width of `active_time` excluding the time point `time + active_point`. All TimeValue points with a timestamp `tp` that satisfies `time <= tp < time + active_time` are in the scope of such a TimeAggregate.

However, in some corner cases, we decided to include TimeValue points on the right border of TimeAggregate, leading to inconsistent behavior. In particular, when an interval is requested that stretches beyond the current last raw data point or starts exactly at the last data point, the response TimeAggregate gets clamped to the time stamp of the last data point, but the data point is included in the TimeAggregate. This is inconsistent with the half-openness used in most other cases.

However, this gives rise to some possibly unexpected behavior. 
- [ ] A TimeAggregate of an individual time point with a zero `active_time` doesn't contain anything. Should we change the constructor accordingly?
- [ ] Requesting the last few data points with setting the requested end to some future time point, won't include the very last data point. There is the LAST_VALUE request type though.

### PR DESCRIPTION
**Pull request by tilsche**
addressing #28

### CODE REVIEW

File: src/metric.cpp [hunk 1]
```diff
@@ -129,100 +177,26 @@ Aggregate Metric::aggregate(hta::TimePoint begin, hta::TimePoint end)
...
     end = std::clamp(end, r.first, r.second);
+    [[maybe_unused]] const auto expected_active_time = end - begin;
 
     auto interval = interval_min_;
     auto next_begin = interval_end(begin - Duration(1), interval);
     auto next_end = interval_begin(end, interval);
 
-    Aggregate a;
-
     if (next_begin >= next_end)
```
Comment (bmario) [inline src/metric.cpp:188]: add a comment, why we return aggregate_raw here

File: src/metric.cpp [hunk 2]
```diff
@@ -129,100 +177,26 @@ Aggregate Metric::aggregate(hta::TimePoint begin, hta::TimePoint end)
...
-            else
-            {
-                a += Aggregate(tv.value, tv.time - previous_time);
-            }
-            previous_time = tv.time;
-        }
-        return a;
+        return aggregate_raw(begin, end);
     }
+    Aggregate a;
```
Comment (bmario) [inline src/metric.cpp]:
```suggestion
    }
    
    Aggregate a;
```

**Review by bmario — COMMENTED** [review]
Just minor things. I also tried to find cases, where stuff breaks, but wasn't able to.

So LGTM.
